### ISSUE TITLE
Specifying Elasticsearch URL without docker run -e

### ISSUE THREAD

**Issue by scrisenbery** [docker-library/kibana#22]
I'm using Kubernetes to define my containers which means I don't use the `docker run` command. I am trying to have Kubernetes set the environment variable in the container but it still doesn't start up properly. I also didn't get it to work by just mounting a file into the config directory.

Here's the error I've been getting:

```
{"name":"Kibana","hostname":"kibana-rc-3iatx","pid":1,"level":50,"err":
{"message":"Service Unavailable","name":"Error","stack":"Error: Service Unavailable\n
    at respond (/opt/kibana/src/node_modules/elasticsearch/src/lib/transport.js:235:15)\n
    at checkRespForFailure (/opt/kibana/src/node_modules/elasticsearch/src/lib/transport.js:203:7)\n
    at HttpConnector.<anonymous> (/opt/kibana/src/node_modules/elasticsearch/src/lib/connectors/http.js:156:7)\n
    at IncomingMessage.bound (/opt/kibana/src/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)\n
    at IncomingMessage.emit (events.js:117:20)\n
    at _stream_readable.js:944:16\n
    at process._tickCallback (node.js:442:13)"},"msg":"","time":"2015-11-20T21:14:39.777Z","v":0}

{"name":"Kibana","hostname":"kibana-rc-3iatx","pid":1,"level":60,"err":
{"message":"Service Unavailable","name":"Error","stack":"Error: Service Unavailable\n
    at respond (/opt/kibana/src/node_modules/elasticsearch/src/lib/transport.js:235:15)\n
    at checkRespForFailure (/opt/kibana/src/node_modules/elasticsearch/src/lib/transport.js:203:7)\n
    at HttpConnector.<anonymous> (/opt/kibana/src/node_modules/elasticsearch/src/lib/connectors/http.js:156:7)\n
    at IncomingMessage.bound (/opt/kibana/src/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)\n
    at IncomingMessage.emit (events.js:117:20)\n
    at _stream_readable.js:944:16\n
    at process._tickCallback (node.js:442:13)"},"msg":"","time":"2015-11-20T21:14:39.779Z","v":0}
```

What's the best way to go about this?

**Comment by scrisenbery** [comment]
And I am really having trouble understanding what the entrypoint script is doing. It's pretty obvious what it's trying to do but I can't understand how it's actually accomplishing any of that.

**Comment by scrisenbery** [comment]
Appears to be a 503 error from elasticsearch causing the issue, but I can't verify that Kibana is trying to connect to the right one at the moment.
